networks:
  probe-lang:
    name: probe-lang

services:

  pg:
    image: postgis/postgis:18-master
    container_name: probe-lang-pg
    restart: always
    mem_limit: 700M
    environment:
      POSTGRES_PASSWORD: "pI9Tm1CWZwBucPPULcnS"
    ports:
      - "18401:5432"
    volumes:
      - ${APP_DATA_ROOT}/postgres-data:/var/lib/postgresql
      - ./pg-init:/docker-entrypoint-initdb.d:ro
    networks:
      - probe-lang
    command:
      - "docker-entrypoint.sh"
      - "-c"
      - "max-connections=800"

  pg2:
    image: postgis/postgis:18-master
    container_name: probe-lang-pg2
    restart: always
    mem_limit: 700M
    environment:
      POSTGRES_PASSWORD: "pI9Tm1CWZwBucPPULcnS"
    ports:
      - "18403:5432"
    volumes:
      - ${APP_DATA_ROOT}/postgres-data2:/var/lib/postgresql
      - ./pg-init:/docker-entrypoint-initdb.d:ro
    networks:
      - probe-lang
    command:
      - "docker-entrypoint.sh"
      - "-c"
      - "max-connections=800"

  pg-test:
    image: postgis/postgis:18-master
    container_name: probe-lang-pg-test
    restart: always
    mem_limit: 700M
    environment:
      POSTGRES_PASSWORD: "xHy4Jy3AyGFEiHt6IirT"
    ports:
      - "18402:5432"
    volumes:
      - ${APP_DATA_ROOT}/postgres-data-test:/var/lib/postgresql
      - ./pg-init-test:/docker-entrypoint-initdb.d:ro
    networks:
      - probe-lang
    command:
      - "docker-entrypoint.sh"
      - "-c"
      - "max-connections=800"
